### ISSUE TITLE
Update prefix for NI local authorities

### ISSUE THREAD

**Issue by KDuerden** [drkane/find-that-charity#54]
NI LA have LAN prefix here: https://dev.findthatcharity.uk/orgid/source/lan
It should be GB-LANI http://org-id.guide/list/GB-LANI

**Comment by drkane** [comment]
Fixed here: https://github.com/drkane/find-that-charity-scrapers/commit/6951cad47ac82b1ca5e7e8ad64ca0f803e701861 - But still need to delete the existing records & source

**Comment by KDuerden** [comment]
I noticed the prefix is still wrong in Dev version of FTC. Is the fix going into your new developments for data store?

**Comment by drkane** [comment]
Yep. It's in the dev dev version: https://ftc.ftc.dkane.net/orgid/GB-LANI-ANN
